### ISSUE TITLE
Test run fails

### ISSUE THREAD

**Issue by b-brankovics** [chjiao/PEHaplo#10]
Hi Jiao,

I am having problem getting `PEHaplo` to run. I think all the requirements are installed correctly, but I am not sure how to test whether that is true. I tried following the README and created an `assembly` folder in the root folder of the repo. Then changed directory to the assembly folder and ran `python ../pehaplo.py -f1 ../raw_test_data/virus_1.fa -f2 ../raw_test_data/virus_2.fa -l 180 -l1 210 -r 250 -F 600 -std 150 -n 3 -correct yes` that crashed after a while with the following error:

```
# gt readjoiner overlap (version 1.2)
# number of reads in filtered readset = 27066
# number of irreducible suffix-prefix matches = 27088
# average irreducible SPM/read = 1.00
# number of transitive suffix-prefix matches = 1351014
Number of total reads:  27066
Number of paired reads: 11472
Number of unpaired reads:       15594
Graph construction finished!
Traceback (most recent call last):
  File "/home/microadmin/Programs/PEHaplo/tools/Seperate_strand_single_pair.py", line 480, in <module>
    plus_reads_dict, minus_reads_dict = BFS_tranverse_graph_pair(G, read_db, des_list, starting_nodes[0], pair1_dict, pair2_dict)
  File "/home/microadmin/Programs/PEHaplo/tools/Seperate_strand_single_pair.py", line 280, in BFS_tranverse_graph_pair
    candidate_nodes.extend(G.predecessors(vertex))
AttributeError: 'dictionary-keyiterator' object has no attribute 'extend'
Traceback (most recent call last):
  File "../pehaplo.py", line 157, in <module>
    main()
  File "../pehaplo.py", line 85, in main
    subprocess.check_call('python "%s"/tools/Seperate_strand_single_pair.py samp.des samp_edges.txt kept_num.fa kept_pairs.txt' % base_path, shell=True)
  File "/opt/miniconda3/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'python "/home/microadmin/Programs/PEHaplo"/tools/Seperate_strand_single_pair.py samp.des samp_edges.txt kept_num.fa kept_pairs.txt' returned non-zero exit status 1
```

Is this a bug or is there something wrong with the installation? Could you maybe create **docker image of a working setup** that could be used as an alternative to the complicated manual installation of the requirements?

Thanks for your help in advance!

Kind regards,
Balazs

**Comment by maciejmotyka** [comment]
I confirm that. This test example fails with the same error. Also, the other test fails as well.
To replicate: 
1. Create a fresh conda environment. Activate it.
2. Install dependencies mentioned in the [Guidance](https://github.com/chjiao/TAR-VIR)
3. Clone the [PEHaplo repo](https://github.com/chjiao/PEHaplo/)
4. Make an assembly directory and cd into it
5. Execute the tests
```
conda create -n pehaplo_test python=2.7
conda activate pehaplo_test
conda install networkx=1.11 Karect bamtools==2.4.0 apsp sga samtools bowtie2 overlap_extension genometools-genometools
git clone https://github.com/chjiao/PEHaplo.git
cd PEHaplo
mkdir assembly
cd assembly
```
The test:
`python ../pehaplo.py -f1 ../raw_test_data/virus_1.fa -f2 ../raw_test_data/virus_2.fa -l 180 -l1 210 -r 250 -F 600 -std 150 -n 3 -correct yes`
fails at the same point and with the same errors as mentioned by [b-brankovics](https://github.com/chjiao/PEHaplo/issues/10#issue-361622818).

The other test also fails:
```
python ../apsp_overlap_clique.py ../processed_test_data/Plus_strand_reads.fa ../processed_test_data/pair_end_connections.txt 180 250 600 210

These are your choices:
File name:sequences.txt
Output: All overlaps are shown 
Sorting:  No Sorting
Number of threads:4
Minimum Match Length:180
Distribution Method: Divide k strings equally between the processors
----------------------
Size of File:6793315
Number of Strings: K 27065
Size of strings:6766250
Creating tree: 
User Time for Constructing tree with no sorting required: 21.482 ms
User Time for finding all pairs using brute force: 1.51454
The nodes of the whole graph is: 27065; the edges of the whole graph is: 1378102.
The nodes of the subgraph is: 27065; the edges of the subgraph is: 1378102.
22302
1
Traceback (most recent call last):
  File "../apsp_overlap_clique.py", line 350, in <module>
    G_subgraph = linear_merge_linked_cliques(G_subgraph, G_un_subgraph, read_node_map, read_db, 4)
  File "../apsp_overlap_clique.py", line 211, in linear_merge_linked_cliques
    DFS_collapse_graph(result, read_node_map, read_db)
  File "../apsp_overlap_clique.py", line 117, in DFS_collapse_graph
    if G.out_degree(vertex)==1 and G.in_degree(G.successors(vertex)[0])==1:  # collapse
TypeError: 'dictionary-keyiterator' object has no attribute '__getitem__'
```
I'm using Ubuntu 19.04. Attached is the result of `conda list`, so you can check the exact versions of packages that were installed.
As the issues may be caused by changes in the code of some of the dependencies, a knowledge of the exact versions that you were using when running the program would be very helpful. Alternatively packaging it into a Docker container would resolve this and future problems.
Thanks a lot!

**Comment by maciejmotyka** [comment]
I have been able to resolve both issues by adding numpy and scipy to the environment, as pointed out [here](https://github.com/chjiao/PEHaplo/issues/2).
```
$ conda create -n pehaplo python=2.7 numpy scipy networkx=1.11 karect genometools-genometools sga samtools bowtie2 apsp
$ conda activate pehaplo
```
