### ISSUE TITLE
Fail in contig correction

### ISSUE THREAD

**Issue by wangxw1023** [chjiao/PEHaplo#13]
The command is: python pehaplo.py -f1 PV194D.virus_recruit_1.fa -f2 PV194D.virus_recruit_2.fa -l 100 -l1 120 -t 30 -r 150 -F 375 -std 100 -n 3 -correct yes

The error info is: Traceback (most recent call last):
  File "pehaplo.py", line 157, in <module>
    main()
  File "pehaplo.py", line 115, in main
    subprocess.check_call('samtools view -F 4 -S contigs_alignment.sam > contigs_mapped.sam', shell=True)
  File "/home/xiuwan/miniconda2/envs/pehaplo/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'samtools view -F 4 -S contigs_alignment.sam > contigs_mapped.sam' returned non-zero exit status 1

The reason I think is:
 grep -n "contig_529_0" Contigs.fa 
115:>contig_529_0 contig_529_0 NumDuplicates=1
117:>contig_529_0 contig_529_0 NumDuplicates=1

Why there would be two same id in Contigs.fa?

I have completed the other 10 samples, everything is successful, just this sample meet this problem. It's so strange. Right?

Thanks in advance.

**Comment by chjiao** [comment]
Hi, thanks for using PEHaplo. 

Did you check whether the two sequences are actually the same? If so, maybe you can try to manually remove one and run the error correction again. 

I do not know what is the exact reason for generating two contigs with the same ids.
